CREATE DATABASE IF NOT EXISTS book_db;
CREATE DATABASE IF NOT EXISTS borrow_db;
CREATE DATABASE IF NOT EXISTS customer_db;
CREATE DATABASE IF NOT EXISTS payment_db;
CREATE DATABASE IF NOT EXISTS notification_db;